backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/assets/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "content/docs" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "hidden"}
      - {label: "bookToc", name: "booktoc", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown"}
