name: Create Release
on:
  push:
    branches: 
      - master
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get current date
        id: current-date
        run: |
          echo "::set-output name=date-slug::$(date '+%m-%d-%Y')"
          echo "::set-output name=date-long::$(date '+%B %d, %Y')"
          echo "::set-output name=date-slug-last-month::$(date -d "today -1 month" "+%m-%d-%Y")"
          echo "::set-output name=date-long-last-month::$(date -d "today -1 month" "+%B %d, %Y")"
          

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: V-${{ steps.current-date.outputs.date-slug }}
          release_name: ${{ steps.current-date.outputs.date-long }} Release
          body: |
            What changed?
            See the changes from the last month here
            [${{ steps.current-date.outputs.date-long-last-month }} updated to ${{ steps.current-date.outputs.date-long }}](https://github.com/ledstrain/wiki.ledstrain.org/compare/V-${{ steps.current-date.outputs.date-slug }}...V-${{ steps.current-date.outputs.date-slug-last-month }})
          draft: true
          prerelease: false



      - name: Archive source of site
        run: |
          zip -8 -r ${{ runner.temp }}/V-${{ steps.current-date.outputs.date-slug }}-source.zip ./

      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=month::$(date '+%m')"

      - name: Cache Hugo Assets
        id: cache-hugo-assets
        uses: actions/cache@v1
        with:
          path: /tmp/hugo_cache
          key: hugo-${{ steps.current-month.outputs.month }}
          restore-keys: |
            hugo-${{ steps.current-month.outputs.month }}
            hugo-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Stats
        env:
          MATOMO_API: ${{ secrets.MATOMO_API }}
          MATOMO_BASEURL: ${{ secrets.MATOMO_BASEURL }}
          BUILD: "SOURCE"
        run: bash '.github/scripts/download-assets.sh' 'assets'

      - name: Build Hugo with relative URL for Release asset
        env:
          HUGO_RELATIVEURLS: true
        run: hugo

      - name: Archive compiled site
        run: |
          zip -8 -r ${{ runner.temp }}/V-${{ steps.current-date.outputs.date-slug }}.zip public
          
      - name: Upload Source Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ runner.temp }}/V-${{ steps.current-date.outputs.date-slug }}-source.zip
          asset_name: V-${{ steps.current-date.outputs.date-slug }}-source.zip
          asset_content_type: application/zip

      - name: Upload Compiled Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ runner.temp }}/V-${{ steps.current-date.outputs.date-slug }}.zip
          asset_name: V-${{ steps.current-date.outputs.date-slug }}.zip
          asset_content_type: application/zip
