name: download-assets

on:
  schedule:
    - cron:  '25 2 * * 0'

    
jobs:
  download-images:
    runs-on: ubuntu-latest
    steps:
    - name: Stats
      env:
        MATOMO_API: ${{ secrets.MATOMO_API }}
        MATOMO_BASEURL: ${{ secrets.MATOMO_BASEURL }}
        BUILD: "COMPILED"
      run: |
        wget 'https://raw.githubusercontent.com/ledstrain/wiki.ledstrain.org/master/.github/scripts/download-assets.sh'
        bash './download-assets.sh' 'public'
                                                                                        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        keepFiles: true
