name: github-pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Get Current Month
      id: current-month
      run: echo "::set-output name=month::$(date '+%m')"

    - name: Cache Hugo Assets
      id: cache-hugo-assets
      uses: actions/cache@v1
      with:
        path: /tmp/hugo_cache
        key: hugo-${{ steps.current-month.outputs.month }}
        restore-keys: |
          hugo-${{ steps.current-month.outputs.month }}
          hugo-
#    - name: Cache htmltest 
#      id: cache-html-assets
#      uses: actions/cache@v1
#      with:
#        path: "tmp/.htmltest"
#        key: ${{ runner.os }}-htmltest-${{ hashfiles('**/refcache.json') }}
#        restore-keys: |
#          ${{ runner.os }}-htmltest-
#          -htmltest-

# Disabled pending https://github.com/actions/cache/issues/106
#    - name: Cache Hugo Assets
#      id: cache-assets
#      uses: actions/cache@v1
#      with:
#        path: ${{ runner.temp }}/hugo_cache
#        key: hugo-${{ hashfiles('**/filecache/**') }}
#        restore-keys: hugo-
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
        
    - name: Build Hugo Testing
      env:
        TESTDIR: ${{ runner.temp }}/publicTesting
        HUGO_ENVIRONMENT: "testing"
        HUGO_RELATIVEURLS: true
      run: hugo -d $TESTDIR

    - name: Test Broken Links
      env:
        TMPDIR: ${{ runner.temp }}
        TESTDIR: ${{ runner.temp }}/publicTesting
      run: bash '.github/scripts/htmltest.sh'
        
#    - name: Spellcheck Action
#      uses: rojopolis/spellcheck-github-actions@0.2.0

    - name: Stats
      env:
        MATOMO_API: ${{ secrets.MATOMO_API }}
        MATOMO_BASEURL: ${{ secrets.MATOMO_BASEURL }}
        BUILD: "SOURCE"
      run: bash '.github/scripts/download-assets.sh' 'assets'
      
    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: gh-pages
        force_orphan: true
