name: github-pages

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '25 2 * * 0'

jobs:
  build-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        fetch-depth: 1

    - name: Get Current Month
      id: current-month
      run: echo "::set-output name=month::$(date '+%m')"

    - name: Cache Hugo Assets
      id: cache-assets
      uses: actions/cache@v1
      with:
        path: /tmp/hugo_cache
        key: hugo-${{ steps.current-month.outputs.month }}
        restore-keys: |
          hugo-${{ steps.current-month.outputs.month }}
          hugo-

# Disabled pending https://github.com/actions/cache/issues/106
#    - name: Cache Hugo Assets
#      id: cache-assets
#      uses: actions/cache@v1
#      with:
#        path: ${{ runner.temp }}/hugo_cache
#        key: hugo-${{ hashfiles('**/filecache/**') }}
#        restore-keys: hugo-
    
    - name: Stats
      env:
        MATOMO_API: ${{ secrets.MATOMO_API }}
      run: |
        wget 'https://raw.githubusercontent.com/ledstrain/wiki.ledstrain.org/master/.github/scripts/download-images.sh'
        bash './download-images.sh'
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo
                                                                                
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        forceOrphan: true


  download-images:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - name: Stats
      env:
        MATOMO_API: ${{ secrets.MATOMO_API }}
      run: |
        wget 'https://raw.githubusercontent.com/ledstrain/wiki.ledstrain.org/master/.github/scripts/download-images.sh'
        bash './download-images.sh'
                                                                                        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        keepFiles: true
