name: github-pages                                                              
                                                                                
on:                                                                             
  push:                                                                         
    branches:                                                                   
    - master                                                                    
                                                                                
jobs:                                                                           
  build-deploy:                                                                 
    runs-on: ubuntu-18.04                                                     
    steps:                                                                      
    - uses: actions/checkout@v1                                                 
      with:                                                                     
        submodules: true                                                        

    - name: Cache Hugo Assets
      id: cache-assets
      uses: actions/cache@v1
      with:
        path: /tmp/hugo_cache
        key: ${{ runner.os }}-hugo-

    - name: Setup Hugo                                                          
      uses: peaceiris/actions-hugo@v2                                           
      with:                                                                     
        hugo-version: 'latest'                                                  
        extended: true                                                          
                                                                                
    - name: Build                                                               
      run: hugo
                                                                                
    - name: Deploy                                                              
      uses: peaceiris/actions-gh-pages@v2                                       
      env:                                                                      
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}                              
        PUBLISH_BRANCH: gh-pages                                                
        PUBLISH_DIR: ./public
      with:
        forceOrphan: true
