name: pull-request

on: 
  pull_request:
    branches:
      master


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        fetch-depth: 20
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Testing
      env:
        HUGO_ENVIRONMENT: "testing"
        HUGO_RELATIVEURLS: true
      run: hugo -d "${{ runner.temp }}/publicTesting"

    - name: Test Broken Links
      env:
        TESTDIR: "${{ runner.temp }}/publicTesting"
      run: bash '.github/scripts/htmltest.sh'
