name: stats

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '25 2 * * 0'
    - cron:  '*/5 * * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Stats
      run: |
        mkdir -p public/docs/appendix/meta/stats/img
        wget 'https://track.xyzz.work/index.php?module=API&method=ImageGraph.get&idSite=3&apiModule=UserCountry&apiAction=getCountry&token_auth=${{ secrets.MATOMO_API }}&graphType=horizontalBar&period=month&date=today&width=800&height=400' -O public/docs/appendix/meta/stats/img/visits_country.png
        wget 'https://track.xyzz.work/index.php?module=API&method=ImageGraph.get&idSite=3&apiModule=VisitsSummary&apiAction=get&token_auth=${{ secrets.MATOMO_API }}&graphType=evolution&period=day&date=previous30&width=800&height=400' -O public/docs/appendix/meta/stats/img/visits_summary.png
                                                                                
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        keepFiles: true
